name: "OpenSAFELY Research Action"
description: "Verifies that OpenSAFELY research repos can run correctly"

inputs:
  directory: 
    description: "Directory containing OpenSAFELY project"
    required: false
    default: . 
  actions:
    description: "Names of project actions to run during tests (default 'run_all')"
    required: false
    default: "run_all"

outputs:
  issue:
    description: "url of issue created"
    value: ${{ steps.datasets.outputs.issue }}

runs:
  using: "composite"
  steps:
    - name: Install opensafely
      shell: bash
      run: |
          python3 -m pip install --quiet --upgrade opensafely
          opensafely --version
    - name: Check codelists
      shell: bash
      working-directory: ${{ inputs.directory }}
      run: opensafely codelists check
    - name: Run project
      shell: bash
      working-directory: ${{ inputs.directory }}
      run: opensafely run ${{ inputs.actions }} --continue-on-error --timestamps --format-output-for-github
    - name: Parse stats logs
      if: ${{ env.HONEYCOMB_API_KEY }}
      shell: bash
      run: opensafely extract-stats
      working-directory: ${{ inputs.directory }}
    - name: Send extracted stats to honeycomb
      if: ${{ env.HONEYCOMB_API_KEY }}
      shell: bash
      run: |
        docker run --pull=missing --rm \
        --volume $GITHUB_ACTION_PATH/${{ inputs.directory }}/metadata/extracted_stats.json:/src/log_file.json \
        --env HONEYCOMB_WRITE_KEY=$HONEYCOMB_API_KEY \
        --env DATASET=research-action \
        ghcr.io/opensafely-core/honeytail:latest
