inputs:
  directory: 
    description: "Directory containing OpenSAFELY project"
    required: false
    default: . 
  users:
    description: "@names of users who should be notified on dataset failure"
    required: false
    default: "@amirmehrkar @Jongmassey @bloodearnest @inglesp"

outputs:
  issue:
    description: "url of issue created"
    value: ${{ steps.datasets.outputs.issue }}

runs:
  using: "composite"
  steps:
    - name: Install opensafely
      shell: bash
      run: |
          python3 -m pip install --quiet --upgrade opensafely
          opensafely --version
    - name: Check codelists
      shell: bash
      working-directory: ${{ inputs.directory }}
      run: opensafely codelists check
    - name: Check datasets
      shell: bash
      id: datasets
      working-directory: ${{ inputs.directory }}
      run: |
        success=true
        OUTPUT=$(opensafely check 2>&1) || success=false
        echo "$OUTPUT"
        # exit early if we're all good
        test "$success" = "true" && exit 0

        BODY=$(cat << EOF
        Dataset check for $GITHUB_REPOSITORY at $GITHUB_SHA:
        \`\`\`
        $OUTPUT
        \`\`\`
        ${{ inputs.users }}
        EOF
        )

        ISSUE_URL=$(gh issue create --title "Dataset check fail" --body "$BODY")

        echo "Created issue at $ISSUE_URL"
        echo "::set-output name=issue::$ISSUE_URL"
        exit 1
    - name: Run project
      shell: bash
      working-directory: ${{ inputs.directory }}
      run: opensafely run run_all --continue-on-error --timestamps --format-output-for-github
    - name: Parse stats logs
      if: ${{ env.HONEYCOMB_API_KEY }}
      shell: bash
      run: opensafely extract-stats
      working-directory: ${{ inputs.directory }}
    - name: Send extracted stats to honeycomb
      if: ${{ env.HONEYCOMB_API_KEY }}
      shell: bash
      run: |
        docker run --pull=missing --rm \
        --volume $GITHUB_ACTION_PATH/${{ inputs.directory }}/metadata/extracted_stats.json:/src/log_file.json \
        --env HONEYCOMB_WRITE_KEY=$HONEYCOMB_API_KEY \
        --env DATASET=research-action \
        ghcr.io/opensafely-core/honeytail:latest
