inputs:
  project_dir:
    description: 'run checks against a project in this directory'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: Run opensafely checks
      shell: bash
      run: |
        $GITHUB_ACTION_PATH/action.sh ${{ inputs.project_dir }}
