name: Tests

on: [push]
env:
 GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 STATA_LICENSE: ${{ secrets.STATA_LICENSE }}

jobs:
  test-action:
    runs-on: ubuntu-20.04
    name: Test action
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout gh-research-testing
        uses: actions/checkout@v2
        with:
            repository: opensafely/gh-research-testing
            path: gh-research-testing
      - name: Run action
        uses: ./
        with:
            directory: gh-research-testing
